import { KeyMappings } from '../../types';

export default {
  space: ['livingSpace'],
  slug: ['title'],
  freeFormTexts: [
    'descriptionNote',
    'locationNote',
    'furnishingNote',
    'otherNote',
  ],
  specifications: [
    'plotArea',
    'residentialUnits',
    'floor',
    'numberOfApartments',
    'numberOfRooms',
    'numberOfBedRooms',
    'numberOfBathRooms',
    'numberOfFloors',
    'numberOfCommercialUnits',
    'constructionYear',
    'lastRefurbishment',
    'courtage',
    'constructionPhase',
    'condition',
    'interiorQuality',
    'freeFrom',
    'heatingType',
    'numberOfParkingSpaces',
    'parkingSpaceType',
    'parkingSpacePrice',
    'buildingEnergyRatingType',
    'lodgerFlat',
    'cellar',
    'energyConsumptionContainsWarmWater',
    'handicappedAccessible',
    'guestToilet',
    'guestBathroom',
    'balcony',
    'patio',
    'garden',
    'attic',
    'listed',
    'summerResidencePractical',
    'energyCertificateAvailability',
    'energyPerformanceCertificate',
  ],
} as KeyMappings;
